views/households.py
from flask import Flask, Blueprint, render_template, json, redirect
from flask_mysqldb import MySQL
from flask import request
import os
import database.db_connector as db

db_connection = db.connect_to_database()
view_households = Blueprint('view_households', __name__)


@view_households.route('/', methods=['POST', 'GET'])
def households():
    db_connection = db.connect_to_database()

    # Add a new household
    if request.method == 'POST':
        if request.form.get('Add_Household'):
            name = request.form['name']
            address = request.form['address']
            
            # No null inputs
            query = 'INSERT INTO Households (name, address) VALUES (%s, %s);'
            cursor = db.execute_query(db_connection=db_connection, query=query, query_params=(name, address))
            results = cursor.fetchall()
            return redirect('/households')

    # View all households
    if request.method == 'GET':
        query = 'SELECT Households.id_household AS id, name, address FROM Households;'
        cursor = db.execute_query(db_connection=db_connection, query=query)
        results = cursor.fetchall()
    return render_template('households.j2', households=results)


@view_households.route('/households-edit/<int:id>', methods=['POST', 'GET'])
def households_edit(id):
    db_connection = db.connect_to_database()

    # View selected household
    if request.method == 'GET':
        query = 'SELECT * FROM Households WHERE id_household = %s' % (id)
        cursor = db.execute_query(db_connection=db_connection, query=query)
        results = cursor.fetchall()

        # View households
        query2 = "SELECT id_household, name FROM Households;"
        cursor = db.execute_query(db_connection=db_connection, query=query2)
        data = cursor.fetchall()
        return render_template("households-edit.j2", households=results, households_dropdown=data)
    
    # Update selected household
    if request.method == 'POST':
        if request.form.get('Edit_Household'):
            name = request.form['name']
            address = request.form['address']

            # No null inputs
            query = 'UPDATE Households SET Households.name = %s, Households.address = %s WHERE id_household = %s;'
            cursor = db.execute_query(db_connection=db_connection, query=query, query_params=(name, address, id))
            results = cursor.fetchall()
            return redirect('/households')


@view_households.route('/households-delete/<int:id>')
def households_delete(id):
    db_connection = db.connect_to_database()

    query = 'DELETE FROM Households WHERE id_household = "%s";'
    db.execute_query(db_connection=db_connection, query=query, query_params=(id,))
    return redirect('/households')

views/households_inventories.py
from flask import Flask, Blueprint, render_template, json, redirect
from flask_mysqldb import MySQL
from flask import request
import os
import database.db_connector as db

db_connection = db.connect_to_database()
view_households_inventories = Blueprint('view_households_inventories', __name__)

@view_households_inventories.route('/', methods=['POST', 'GET'])
def households_inventories():
    db_connection = db.connect_to_database()

    # Add a new item to a household
    if request.method == 'POST':
        if request.form.get('Add_Households_Inventories'):
            household = request.form['id_household']
            item = request.form['id_item']
            amount_left = request.form['amount_left']
            restock_status = request.form['restock_status']

            # No null inputs
            query = 'INSERT INTO Households_Inventories (id_household, id_item, amount_left, restock_status) VALUES (%s, %s, %s, %s);'
            cursor = db.execute_query(db_connection=db_connection, query=query, query_params=(household, item, amount_left, restock_status))
            results = cursor.fetchall()
            return redirect('/households-inventories')

    # View all household inventory
    if request.method == 'GET':
        query = "SELECT Households_Inventories.id_household_inventory AS id, Households.name AS household, Households_Items.name AS item, Households_Inventories.amount_left AS 'amount left', IF(restock_status=1, 'Restock', 'Inventory') AS 'restock status' FROM Households_Inventories INNER JOIN Households ON Households.id_household = Households_Inventories.id_household INNER JOIN Households_Items ON Households_Items.id_item = Households_Inventories.id_item ORDER BY Households_Inventories.id_household_inventory ASC;"
        cursor = db.execute_query(db_connection=db_connection, query=query)
        results = cursor.fetchall()

        # View households
        query2 = "SELECT id_household, name FROM Households;"
        cursor = db.execute_query(db_connection=db_connection, query=query2)
        results2 = cursor.fetchall()

        # View households items
        query3 = "SELECT id_item, name FROM Households_Items;"
        cursor = db.execute_query(db_connection=db_connection, query=query3)
        results3 = cursor.fetchall()

    return render_template("households-inventories.j2", households_inventories=results, household_dropdown=results2, items_dropdown=results3)


@view_households_inventories.route('/households-inventories-edit/<int:id>', methods=['POST', 'GET'])
def households_inventories_edit(id):
    db_connection = db.connect_to_database()

    # View selected household inventory
    if request.method == 'GET':
        query = "SELECT Households_Inventories.id_household_inventory AS id, Households.name AS household, Households_Items.name AS item, Households_Inventories.amount_left AS 'amount left', Households_Inventories.restock_status AS 'restock status' FROM Households_Inventories INNER JOIN Households ON Households.id_household = Households_Inventories.id_household INNER JOIN Households_Items ON Households_Items.id_item = Households_Inventories.id_item ORDER BY Households_Inventories.id_household_inventory ASC;"
        cursor = db.execute_query(db_connection=db_connection, query=query)
        results = cursor.fetchall()

        # View households
        query2 = "SELECT id_household, name FROM Households;"
        cursor = db.execute_query(db_connection=db_connection, query=query2)
        results2 = cursor.fetchall()
        return render_template("households-inventories-edit.j2", households_inventories=results, household_dropdown=results2)
    
    # Update selected household inventory
    if request.method == 'POST':
        if request.form.get('Edit_Households_Inventories'):
            # id_household = request.form['id_household']
            # id_item = request.form['id_item']
            amount_left = request.form['amount_left']
            restock_status = request.form['restock_status']

            query = 'UPDATE Households_Inventories SET Households_Inventories.amount_left = %s, Households_Inventories.restock_status = %s WHERE id_household_inventory = %s;'
            cursor = db.execute_query(db_connection=db_connection, query=query, query_params=(amount_left, restock_status, id))
            results = cursor.fetchall()
            return redirect('/households-inventories')

@view_households_inventories.route('/households-inventories-delete/<int:id>')
def households_inventories_delete(id):
    db_connection = db.connect_to_database()

    query = "DELETE FROM Households_Inventories WHERE id_household_inventory = '%s';"
    db.execute_query(db_connection=db_connection, query=query, query_params=(id,))
    return redirect('/households-inventories')

views/households_items.py
from flask import Flask, Blueprint, render_template, json, redirect
from flask_mysqldb import MySQL
from flask import request
import os
import database.db_connector as db

db_connection = db.connect_to_database()
view_households_items = Blueprint('view_households_items', __name__)



@view_households_items.route('/', methods=['POST', 'GET'])
def households_items():
    db_connection = db.connect_to_database()

    # Add a new household item
    if request.method == 'POST':
        if request.form.get('Add_Households_Items'):
            item_type = request.form['item_type']
            name = request.form['name']
            best_if_used_by = request.form['best_if_used_by']

            # No null inputs
            query = 'INSERT INTO Households_Items (id_item_type, name, best_if_used_by) VALUES (%s, %s, %s);'
            cursor = db.execute_query(db_connection=db_connection, query=query, query_params=(item_type, name, best_if_used_by))
            results = cursor.fetchall()
            return redirect('/households-items')

    # View household items
    if request.method == 'GET':
        query = "SELECT Households_Items.id_item AS id, Items_Types.name AS 'item type', Households_Items.name AS name, Households_Items.best_if_used_by AS 'best if used by' FROM Households_Items INNER JOIN Items_Types ON Items_Types.id_item_type = Households_Items.id_item_type;"
        cursor = db.execute_query(db_connection=db_connection, query=query)
        results = cursor.fetchall()

        # View item types
        query2 = "SELECT Items_Types.id_item_type, name FROM Items_Types;"
        cursor = db.execute_query(db_connection=db_connection, query=query2)
        results2 = cursor.fetchall()

    return render_template("households-items.j2", households_items=results, items_types_dropdown=results2)


@view_households_items.route('/households-items-edit/<int:id>', methods=['POST', 'GET'])
def households_items_edit(id):
    db_connection = db.connect_to_database()

    # View selected household item
    if request.method == 'GET':
        query = "SELECT Households_Items.id_item AS id, Items_Types.name AS 'item type', Households_Items.name AS name, Households_Items.best_if_used_by AS 'best if used by' FROM Households_Items INNER JOIN Items_Types ON Items_Types.id_item_type = Households_Items.id_item_type;"
        cursor = db.execute_query(db_connection=db_connection, query=query)
        results = cursor.fetchall()
        
        # View item types
        query2 = "SELECT Items_Types.id_item_type, name FROM Items_Types;"
        cursor = db.execute_query(db_connection=db_connection, query=query2)
        results2 = cursor.fetchall()
        return render_template("households-items-edit.j2", results=results)
    
    # Update selected household item
    if request.method == 'POST':
        if request.form.get('Edit_Households_Items'):
            id_item_type = request.form['id_item_type']
            name = request.form['name']
            best_if_used_by = request.form['best_if_used_by']
            
            # No null inputs
            query = 'UPDATE Households_Items SET id_item_type = %s, SET name = %s, SET best_if_used_by = %s WHERE id_item = %s;'
            cursor = db.execute_query(db_connection=db_connection, query=query, query_params=(id_item_type, name, best_if_used_by, id))
            results = cursor.fetchall()
            return redirect('/households-items')


@view_households_items.route('/households-items-delete/<int:id>')
def households_items_delete(id):
    db_connection = db.connect_to_database()

    query = "DELETE FROM Households_Items WHERE id_item = '%s';"
    db.execute_query(db_connection=db_connection, query=query, query_params=(id,))
    return redirect('/households-items')

views/items_types.py
from flask import Flask, Blueprint, render_template, json, redirect
from flask_mysqldb import MySQL
from flask import request
import os
import database.db_connector as db

db_connection = db.connect_to_database()
view_items_types = Blueprint('view_items_types', __name__)


@view_items_types.route("/", methods=["POST", "GET"])
def items_types():
    db_connection = db.connect_to_database()
    
    # Add a new item type
    if request.method == 'POST':
        if request.form.get("Add_Items_Types"):
            name = request.form["name"]
            
            # No null inputs
            query = "INSERT INTO Items_Types (name) VALUES (%s)"
            cursor = db.execute_query(db_connection=db_connection, query=query, query_params=(name,))
            results = cursor.fetchall()
        
            return redirect("/items-types")

    # View item types
    if request.method == 'GET':
        query = 'SELECT Items_Types.id_item_type AS id, name AS "item type" FROM Items_Types;'
        cur = db.execute_query(db_connection=db_connection, query=query)
        results = cur.fetchall()

    return render_template("items-types.j2", items_types=results)


@view_items_types.route("/items-types-edit/<int:id>", methods=["POST", "GET"])
def items_types_edit(id):
    db_connection = db.connect_to_database()

    # View selected item type
    if request.method == "GET":
        query = "SELECT Items_Types.name FROM Items_Types WHERE id_item_type = %s;" % (id)
        cur = db.execute_query(db_connection=db_connection, query=query)
        results = cur.fetchall()

        # View stores
        query2 = "SELECT id_store, name FROM Stores;"
        cur = db.execute_query(db_connection=db_connection, query=query2)
        results2 = cur.fetchall()

        return render_template("items-types-edit.j2", items_types=results, stores_dropdown=results2)

    # Update selected item type
    if request.method == "POST":
        if request.form.get("Edit_Items_Types"):
            name = request.form["name"]

            # No null inputs
            query = "UPDATE Items_Types SET name = %s WHERE id_item_type = %s;"
            cur = db.execute_query(db_connection=db_connection, query=query, query_params=(name, id))
            results = cur.fetchall()

            return redirect("/items-types")


@view_items_types.route("/items-types-delete/<int:id>")
def items_types_delete(id):
    db_connection = db.connect_to_database()
    query = "DELETE FROM Items_Types WHERE id_item_type = '%s';"
    db.execute_query(db_connection=db_connection, query=query, query_params=(id,))
    return redirect("/items-types")

views/stores_inventories.py
from flask import Flask, Blueprint, render_template, json, redirect
from flask_mysqldb import MySQL
from flask import request
import os
import database.db_connector as db

db_connection = db.connect_to_database()
view_stores_inventories = Blueprint('view_stores_inventories', __name__)


@view_stores_inventories.route("/", methods=["POST", "GET"])
def stores_inventories():
    db_connection = db.connect_to_database()

    # Add store inventory
    if request.method == 'POST':
        if request.form.get("Add_Stores_Inventories"):
            id_item_type = request.form["id_item_type"]
            id_store = request.form["id_store"]

            # No null inputs
            query = "INSERT INTO Stores_Inventories (id_item_type, id_store) VALUES (%s, %s)"
            cur = db.execute_query(db_connection=db_connection, query=query, query_params=(id_item_type, id_store))
            results = cur.fetchall()
            return redirect("/stores-inventories")

    # View store inventory
    if request.method == 'GET':
        query = "SELECT Items_Types.name AS 'item type', Stores.name AS store FROM Stores_Inventories INNER JOIN Items_Types ON Items_Types.id_item_type = Stores_Inventories.id_item_type INNER JOIN Stores ON Stores.id_store = Stores_Inventories.id_store;"
        cur = db.execute_query(db_connection=db_connection, query=query)
        results = cur.fetchall()

        # View item types
        query2 = "SELECT Items_Types.id_item_type, name FROM Items_Types;"
        cursor = db.execute_query(db_connection=db_connection, query=query2)
        results2 = cursor.fetchall()

        # View stores
        query3 = "SELECT Stores.id_store, name FROM Stores;"
        cursor = db.execute_query(db_connection=db_connection, query=query3)
        results3 = cursor.fetchall()

    return render_template("stores-inventories.j2", stores_inventories=results, items_types_dropdown=results2, stores_dropdown=results3)


# @view_stores_inventories.route("/stores-inventories-delete/<int:id>")
# def stores_inventories_delete(id):
#     db_connection = db.connect_to_database()
#     query = "DELETE FROM Stores_Inventories WHERE id_item_type = '%s';"
#     db.execute_query(db_connection=db_connection, query=query, query_params=(id,))
#     return redirect("/stores-inventories")

templates/households-edit.j2
{% extends "main.j2" %}


{% block title %}
Households - Edit
{% endblock %}


{% block heading %}
Households - Edit Selection
{% endblock %}


{% block content %}
<form method="POST">
<fieldset>
<legend>Edit a Household</legend>

        <input type="hidden" name="id_household" value="{{request.form['id_household']}}" required="required">
<label>name
    <input type="text" name="name" value="{{ households[0]["name"] }}" size="12" maxlength="45" required="required">
</label>
<br />
<label>address
    <input type="text" name="address" value="{{ households[0]["address"] }}" size="12" maxlength="45" required="required">
</label>

<br />
</fieldset>
<button type="submit" name="Edit_Household" value="Edit Household">Submit</button>
<a href='{{url_for('view_households.households')}}'><input type="button" name="Cancel" value="Cancel"/></a>
</form>
{% endblock %}submit" name="Edit_Household" value="Edit Household">Submit</button>
<a href='{{url_for('view_households.households')}}'><input type="button" name="Cancel" value="Cancel"/></a>
</form>
{% endblock %}

templates/households-inventories-edit.j2
{% extends "main.j2" %}


{% block title %}
Households Inventories - Edit
{% endblock %}


{% block heading %}
Households Inventories - Edit Selection
{% endblock %}


{% block content %}
<form method="POST">
<fieldset>
<legend>Edit a Household Inventory</legend>

{# <label>household
    <input type ="number" name="id_household" size="12" maxlength="45" required="required">
</label>

<br />
<label>item
    <input type="number" name="id_item" size="12" maxlength="45" required="required">
</label> #}

<br />
<label>amount left
    <select name="amount_left" required>
    <option value="">Select amount left</option>
    <option value="Empty">Empty</option>
    <option value="Running Low">Running Low</option>
    <option value="Still Plenty">Still Plenty</option>
    <option value="Fully Stocked">Fully Stocked</option>
    </select>
</label>

<br />    
<label>restock status
  <input type="radio" id="restock_status" name="restock_status" value="1">
    <label for="restock_status">Restock</label>
  <input type="radio" id="restock_status" name="restock_status" value="0">
    <label for="restock_status">Currently Stocked</label>
</label>

<br />
</fieldset>
<button type="submit" name="Edit_Households_Inventories" value="Edit a Household Inventory">Submit</button>
<a href='{{url_for('view_households_inventories.households_inventories')}}'><input type="button" name="Cancel" value="Cancel"/></a>
</form>    
{% endblock %}

templates/households-inventories.j2
{% extends "main.j2" %}


{% block title %}
Households Inventories
{% endblock %}


{% block heading %}
Households Inventories
{% endblock %}


{% block content %}
<table>
<thead>
<tr>
{% if households_inventories %}
    {% for key in households_inventories[0].keys() %}
        <th>{{ key }}</th>
    {% endfor %}
        <th>Edit</th>
        <th>Delete</th>
{% else %}
    <p>There are currently no households inventories listed.</p>
{% endif %}
</tr>

<tbody>
{% for attribute in households_inventories %}
<tr>
    {% for key in attribute.keys() %}
        <td>{{attribute[key]}}</td>
    {% endfor %}
        <td><a href="households-inventories-edit/{{attribute.id}}" />Edit</td>
        <td><a href="households-inventories-delete/{{attribute.id}}" />Delete</td>
</tr>
{% endfor %}
</table>

<br />

<form action="{{url_for('view_households_inventories.households_inventories')}}" method="POST">
<fieldset>
<legend>Add a Household Inventory</legend>
    
<label>household
    <select name="id_household" required>
    <option value="">Select a household</option>
    {% for household in household_dropdown %}
    <option value="{{ household.id_household }}">{{ household.name }}</option>
    {% endfor %}
    </select>
</label>

<br />
<label>item
    <select name="id_item" required>
    <option value="">Select an item</option>
    {% for item in items_dropdown %}
    <option value="{{ item.id_item }}">{{ item.name }}</option>
    {% endfor %}
    </select>
</label>

<br />
<label>amount left
    <select name="amount_left" required>
    <option value="">Select amount left</option>
    <option value="Empty">Empty</option>
    <option value="Running Low">Running Low</option>
    <option value="Still Plenty">Still Plenty</option>
    <option value="Fully Stocked">Fully Stocked</option>
    </select>
</label>

<br />    
<label>restock status
  <input type="radio" id="restock_status" name="restock_status" value="1" required>
    <label for="restock_status">Restock</label>
  <input type="radio" id="restock_status" name="restock_status" value="0" required>
    <label for="restock_status">Currently Stocked</label>
</label>

<br />
</fieldset>
<button type="submit" name="Add_Households_Inventories" value="Add a Household Inventory">Add</button>
</form>    
{% endblock %}

templates/households-items.j2
{% extends "main.j2" %}


{% block title %}
Households Items
{% endblock %}


{% block heading %}
Households Items
{% endblock %}


{% block content %}
<table>
<thead>
{% if households_items %}
<tr>
    {% for key in households_items[0].keys() %}
        <th>{{ key }}</th>
    {% endfor %}
        <th>Delete</th>
{% else %}
    <p>There are currently no households items listed.</p>
{% endif %}
</tr>

<tbody>
    {% for attribute in households_items %}
<tr>
    {% for key in attribute.keys() %}
        <td>{{attribute[key]}}</td>
    {% endfor %}
        <td><a href="households-items-delete/{{attribute.id}}" />Delete</td>
</tr>
{% endfor %}
</table>

<form action="{{url_for('view_households_items.households_items')}}" method="POST">
<fieldset>
<legend>Add a Household Item</legend>

<label>item type
    <select name="item_type">
    <option value="">Select an item type</option>
    {% for type in items_types_dropdown %}
    <option value="{{ type.id_item_type }}">{{ type.name }}</option>
    {% endfor %}
    </select>
</label>

<br />
<label>name
    <input type="text" name="name" size="12" maxlength="45" required="required">
</label>

<br />
<label>best if used by
    <input type="date" name="best_if_used_by" size="12" maxlength="45" required="required">
</label>

<br />
</fieldset>
<button type="submit" name="Add_Households_Items" value="Add a Household Item">Add</button>
</form>
{% endblock %}

templates/households-members-edit.j2
{% extends "main.j2" %}


{% block title %}
Households Members - Edit
{% endblock %}


{% block heading %}
Households Members - Edit Selection
{% endblock %}


{% block content %}
<form method="POST">
<fieldset>
<legend>Edit a Household Member</legend>

<br />
<label>name
    <input type="text" class="form-control" name="name" value="{{ households_members[0]["name"] }}" required=required>
</label>

<br />
<label>household
    <select name="id_household">
    <option value="">Select a household</option>
    {% for household in household_dropdown %}
    <option value="{{ household.id_household }}">{{ household.name }}</option>
    {% endfor %}
    </select>
</label>    

<br />
<label>runner status
    <select name="runner_status" required=required>
    <option value="">Select runner status</option>
    <option value="1">Runner</option>
    <option value="0">Not Runner</option>
    </select>
</label>

<br />
</fieldset>
<button type="submit" name="Edit_Households_Members" value="Edit Household Member">Submit</button>
<a href='{{url_for('view_households_members.households_members')}}'><input type="button" name="Cancel" value="Cancel"/></a>
</form>
{% endblock %}

templates/households.j2
{% extends "main.j2" %}


{% block title %}
Households
{% endblock %}


{% block heading %}
Households
{% endblock %}


{% block content %}
<table>
<thead>
<tr>
{% if households %}
    {% for key in households[0].keys() %}
        <th>{{ key }}</th>
    {% endfor %}
        <th>Edit</th>
        <th>Delete</th>
{% else %}
    <p>There are currently no households listed.</p>
{% endif %}
</tr>

<tbody>
{% for attribute in households %}
<tr>
    {% for key in attribute.keys() %}
        <td>{{attribute[key]}}</td>
    {% endfor %}
        <td><a href="households-edit/{{attribute.id}}" />Edit</td>
        <td><a href="households-delete/{{attribute.id}}" />Delete</td>
</tr>
{% endfor %}
</table>

<br />

<form action="{{url_for('view_households.households')}}" method="POST">
<fieldset>
<legend> Add a Household</legend>

<label>name
    <input type="text" name="name" value="" size="12" maxlength="45" required="required">
</label>

<br />
<label>address
    <input type="text" name="address" value="" size="12" maxlength="145">
</label>

<br />
</fieldset>
<button type="submit" name="Add_Household" value="Add Household">Add</button>
</form>
{% endblock %}

templates/index.j2
{% extends "main.j2" %}


{% block title %}
Home
{% endblock %}


{# {% block heading %}
Home
{% endblock %} #}


{% block content %}
    <div class = "Menu">
    <h3><a href="{{url_for('view_households.households')}}">Households</a></h3>
        <ul>
        <li>Display households available</li>
        <li>Add a new household</li>
        <li>Edit current households</li>
        <li>Delete an existing household</li>
        </ul>
    <h3><a href="{{url_for('view_households_members.households_members')}}">Households Members</a></h3>
        <ul>
        <li>Display members of different households</li>
        <li>Add a new household member</li>
        <li>Edit current household member status</li>
        <li>Delete an existing household member</li>
        </ul>
    <h3><a href="{{url_for('view_households_inventories.households_inventories')}}">Households Inventories</a></h3>
        <ul>
        <li>Display items found in household inventories</li>
        <li>Add new household inventory stock</li>
        <li>Edit current inventory stock</li>
        <li>Delete existing inventory stock</li>
        </ul>
    <h3><a href="{{url_for('view_households_items.households_items')}}">Households Items</a></h3>
        <ul>
        <li>Display household items</li>
        <li>Add a new household item</li>
        <li>Delete an existing household item</li>
        </ul>
    <h3><a href="{{url_for('view_items_types.items_types')}}">Items Types</a></h3>
        <ul>
        <li>Display item types found in households</li>
        <li>Add a new item type</li>
        </ul>
    <h3><a href="{{url_for('view_stores_inventories.stores_inventories')}}">Stores Inventories</a></h3>
        <ul>
        <li>Display item types found in store inventories</li>
        <li>Add an item type to a store's inventory</li>
        </ul>
    <h3><a href="{{url_for('view_stores.stores')}}">Stores</a></h3>
        <ul>
        <li>Display stores available</li>
        <li>Add a new store</li>
        <li>Edit current stores</li>
        <li>Delete an existing store</li>
        </ul>
    </div>
{% endblock %}

templates/items-types.j2
{% extends "main.j2" %}


{% block title %}
Items Types
{% endblock %}


{% block heading %}
Items Types
{% endblock %}


{% block content %}
    <table>
        <thead>
            <tr>
            {% for key in items_types[0].keys() %}
                <th>{{ key }}</th>
            {% endfor %}
                {# <th>Delete</th> #}
            <tr>
        <tbody>
        {% for attribute in items_types %}
            <tr>
                {% for key in attribute.keys() %}
                <td>{{attribute[key]}}</td>
                {% endfor %}
                {# <td><a href="{{url_for('items_types')}}" />Delete</td>                 #}
            </tr>
        {% endfor %}
    </table>

    <br />

<form method="POST">
    <fieldset><legend>Add an Item Type</legend>
    <label>name
        <input type="text" name="name" size="12" maxlength="45" required="required">
    </label>
    <br />
    <button type="submit" name="Add_Items_Types" value="Add an Item Type">Add</button>
    </fieldset>
    </form>
{% endblock %}

templates/main.j2
<html>
<head>

<style>
#Nav {
    display: inline;
}
#Header {text-align: center;
}
</style>

    <title>
    {% block title %}
    <! -- Placeholder for Page Title -->
    {% endblock %} - Project Restock
    </title>
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}" />

</head>

<body>

    <div>
        <ul>
            <li id="Nav"><a href="{{url_for('index')}}">Index || </a></li>
            <li id="Nav"><a href="{{url_for('view_households.households')}}">Households || </a></li>
            <li id="Nav"><a href="{{url_for('view_households_members.households_members')}}">Households Members || </a></li>
            <li id="Nav"><a href="{{url_for('view_households_inventories.households_inventories')}}">Households Inventories || </a></li>
            <li id="Nav"><a href="{{url_for('view_households_items.households_items')}}">Households Items || </a></li>
            {# <li id="Nav"><a href="{{url_for('view_items_types.items_types')}}">Items Types || </a></li>
            <li id="Nav"><a href="{{url_for('view_stores_inventories.stores_inventories')}}">Stores Inventories || </a></li>
            <li id="Nav"><a href="{{url_for('view_stores.stores')}}">Stores</a></li> #}

        </ul>
    </div>

    <h1 id="Header">
    Project Restock
    </h1>

    <p id="Header">No more store run planning! Find your items and know before you go.</p>
    
    <h1 id="title">
    {% block heading %}
    <!-- Placeholder for Page Header -->
    {% endblock %}
    </h1>

    <div id="content">
    {% block content %}
    <!-- Placeholder for Page Content -->
    {% endblock %}
    </div>
    
</body>
</html>

templates/stores-inventories.j2
{% extends "main.j2" %}


{% block title %}
Stores Inventories
{% endblock %}


{% block heading %}
Stores Inventories
{% endblock %}


{% block content %}
<table>
<thead>
{% if stores_inventories %}
<tr>
    {% for key in stores_inventories[0].keys() %}
        <th>{{ key }}</th>
    {% endfor %}
        {# <th>Delete</th> #}
{% else %}
    <p>There are currently no stores inventories listed.</p>
{% endif %}
</tr>

<tbody>
    {% for attribute in stores_inventories %}
<tr>
    {% for key in attribute.keys() %}
        <td>{{attribute[key]}}</td>
    {% endfor %}
        {# <td><a href="{{url_for('view_stores_inventories.stores_inventories')}}" />Delete</td> #}
</tr>
{% endfor %}
</table>

    <br />

    <form method="POST">
    <fieldset><legend> Add a Store Inventory</legend>

        <label>item type
            <select name="id_item_type">
            <option value="">Select an item type</option>
            {% for type in items_types_dropdown %}
            <option value="{{ type.id_item_type }}">{{ type.name }}</option>
            {% endfor %}
            </select>
        </label>
        
        <br />

        <label>store
            <select name="id_store">
            <option value="">Select a store</option>
            {% for store in stores_dropdown %}
            <option value="{{ store.id_store }}">{{ store.name }}</option>
            {% endfor %}
            </select>
        </label>

    </fieldset>
    <button type="submit" name="Add_Stores_Inventories" value="Add a Store Inventory">Add</button>
    </form>
{% endblock %}